# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2022, Linaro Limited
# Copyright 2025 Arm Limited and/or its affiliates <open-source-office@arm.com>
#

obj-$(CONFIG_FWU_MULTI_BANK_UPDATE) += fwu.o
obj-$(CONFIG_FWU_MDATA_GPT_BLK) += fwu_gpt.o
obj-$(CONFIG_FWU_MDATA_MTD) += fwu_mtd.o
obj-$(CONFIG_FWU_MDATA_V1) += fwu_v1.o
obj-$(CONFIG_FWU_MDATA_V2) += fwu_v2.o
obj-$(CONFIG_FWU_ARM_PSA) += fwu_arm_psa.o
